### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by MrDoni98** [ImagicalCorp/ImagicalMine#413] opened 2015-12-26 15:47 UTC
Error: Call to a member function setHeldItemSlot() on null
File: /src/pocketmine/Player
Line: 1811
Type: E_ERROR

Code:
[1802] 			$this->close($this->getLeaveMessage(), $ev->getKickMessage());
[1803] 			
[1804] 			return;
[1805] 		}
[1806] 		
[1807] 		if($this->isCreative()){
[1808] 			$this->inventory->setHeldItemSlot(0);
[1809] 		}
[1810] 		else{
[1811] 			$this->inventory->setHeldItemSlot($this->inventory->getHotbarSlotIndex(0));
[1812] 		}

**Comment by thebigsmileXD** [comment] 2015-12-26 16:04
Thats an official PocketMine crash, post it there please. That was reported once by me, but they just closed it and never fixed it.

**Comment by MrDoni98** [comment] 2015-12-26 16:07
sorry its plugin error ))

**Comment by Tee7even** [comment] 2015-12-26 16:48
@thebigsmileXD But it can be fixed in IM, isn't it?

**Comment by BlackShadow1** [comment] 2015-12-26 16:51
@Tee7even yes, it can be fixed.

**Comment by PeratX** [comment] 2015-12-26 16:52
Yes.This is caused by inventory null when player logout

**Comment by BlackShadow1** [comment] 2015-12-26 16:54
@PeratX if you know the fix, make a pull request

**Comment by PeratX** [comment] 2015-12-26 16:56
@BlackShadow1 I will have a try

**Comment by BlackShadow1** [comment] 2015-12-26 16:58
Well. Good luck.

**Comment by thebigsmileXD** [comment] 2015-12-26 18:47
I was told this is plugin reason ant they closed the issue.
The Plugin you use is ReasonWL?

**Comment by keithkfng** [comment] 2015-12-26 20:46
https://github.com/ImagicalCorp/ImagicalMine/blob/master/CONTRIBUTING.md
Doesn't match them.

**Closed by keithkfng** 2015-12-26 20:46 UTC
