### ISSUE TITLE
latest build. food can't be consumed 

### ISSUE THREAD

**Issue by Tolo0** [ImagicalCorp/ImagicalMine#454] opened 2015-12-28 21:43 UTC
Just started using build #255 and now no food can  be consumed.  Players on my server are literally starving to death 😅

**Comment by PocketKiller** [comment] 2015-12-28 21:43
can't eat? can i have a pic?

**Comment by Tolo0** [comment] 2015-12-28 21:44
U can eat. But u basically eat no stop. It can't be consumed

**Comment by Tolo0** [comment] 2015-12-28 21:51
It seems any food u already have when server reboots works fine. But any food u buy. Doesn't work

**Comment by PocketKiller** [comment] 2015-12-28 21:53
buy?

**Comment by PocketKiller** [comment] 2015-12-28 21:53
as i know that happens because of lag, create a Test server with no plugins and test.

**Comment by dterweij** [comment] 2015-12-29 02:21
Food you already have -> you can eat.
Food you get from a Kit (AdvanceKits for example) -> you can eat.
Food you buy (from a economy shop) does not work. When you want to eat, it animates that you eat but hunger does not become less. 
Serious bug indeed.

**Comment by thebigsmileXD** [comment] 2015-12-29 08:51
Just saying: me and @matcracker were on the Server yesterday (5.175.226.133:19133) and it worked alright. Are you sure you have the latest build?

**Comment by Tolo0** [comment] 2015-12-29 09:40
Just tested it on my test server that had 0% lagg. Any food bought with EconomyShop buy signs. Don't work until reboot. It's like the food isn't registered lol.

**Comment by Tolo0** [comment] 2015-12-29 09:42
![screenshot_2015-12-29-09-38-01](https://cloud.githubusercontent.com/assets/13458191/12032457/7106e8f4-ae10-11e5-9d4f-bbb0a803c610.png)

**Comment by thebigsmileXD** [comment] 2015-12-29 09:44
Again: are you sure you are on the latest build?
by the way.. try opening your inventory and closing it again.
Can i have your ip so i can test?

**Comment by Tolo0** [comment] 2015-12-29 09:51
I'm on build #255 atm haven't updated yet. Ip is 198.50.199.21

**Comment by thebigsmileXD** [comment] 2015-12-29 09:54
I also use 255 currently. But i haven't tested with pe, just wih win 10

**Comment by thebigsmileXD** [comment] 2015-12-29 09:58
Tested. They work after you drop them on the ground..

**Comment by thebigsmileXD** [comment] 2015-12-29 09:58
@Tolo0 can you get on? i want to test more food, but without money?

**Comment by thebigsmileXD** [comment] 2015-12-29 10:02
@matcracker saw ya lefting :eyes:

**Comment by thebigsmileXD** [comment] 2015-12-29 10:10
Seems to be plugin fault, but i'll try to fix it.

**Comment by thebigsmileXD** [comment] 2015-12-29 10:16
```php
$player->getInventory()->addItem($item);
```
That might be the problem

**Comment by thebigsmileXD** [comment] 2015-12-29 10:26
Yea.. that was it. There was a function added in PlayerInventory.php which shouldn't be there.
@Tolo0 Can you install the latest version?

**Comment by Tolo0** [comment] 2015-12-29 10:33
I'll do it now and inform

**Comment by Tolo0** [comment] 2015-12-29 10:39
Still doesn't work 😣

**Comment by thebigsmileXD** [comment] 2015-12-29 11:42
Place a sign.. when they drop and take up it works.

**Comment by linuzo** [comment] 2016-01-03 21:32
Yeah I can confirm this issue.. However it seems to work with Genysis for some reason..

**Comment by thebigsmileXD** [comment] 2016-01-03 21:40
Because the genisys food is still basic like every other pm version

**Comment by ZombiePower** [comment] 2016-01-06 02:40
fixed?

**Comment by thebigsmileXD** [comment] 2016-01-06 08:16
How should i fix this when i work on rails. I close issues when i fixed it, so don't spam "fixed?" Everywhere

**Comment by zzm317** [comment] 2016-01-08 13:59
Already added food craftingmanager

**Comment by thebigsmileXD** [comment] 2016-01-08 14:01
This actually isn't plugin fault. BattleKit has the sign. every plugin that uses ```getInventory()->add()```

**Comment by thebigsmileXD** [comment] 2016-01-08 14:04
I'll fix that.

**Comment by zzm317** [comment] 2016-01-08 14:06
@thebigsmileXD =-=food can add hunger and can be crafted=-=
why you reopen it==

**Comment by thebigsmileXD** [comment] 2016-01-08 14:10
@zzm317 The problem was not the crafting of food..
> Just tested it on my test server that had 0% lagg. Any food bought with EconomyShop buy signs. Don't work until reboot. It's like the food isn't registered lol.

The issue is you can't eat food added to the inventory via ->add()

**Comment by zzm317** [comment] 2016-01-08 14:13
@thebigsmileXD OK ,I know...

**Comment by thebigsmileXD** [comment] 2016-01-08 15:18
new issue for this https://github.com/ImagicalCorp/ImagicalMine/issues/578

**Closed** 2016-01-08 15:18 UTC
Labels: Possibly Fixed
