### ISSUE TITLE
Suggestion to fix that bug with respawning?

### ISSUE THREAD

**Issue by Naniiii** [ImagicalCorp/ImagicalMine#214] opened 2015-12-04 16:47 UTC
Hey guys. As I saw that there are issues related to respawning I wondered if I could help out as well,

I recently found out that the /kill command works fine when it comes to respawning. When a player gets that bug, he/she has to relog. But if you insert the /kill command from a console or op acc on that player while he/she is bugged and can't respawn, the respawn buttons will show up.

Here is an example if my english is bad :

player A kills player B

player B glitches and can't respawn because the buttons are not showing

//FIX// CONSOLE : /kill Player B while he is still on but glitched

player B can see the respawn buttons and respawn

Maybe this is a temporary fix? or idk?

**Comment by Naniiii** [comment] 2015-12-04 16:50
I know this may not be the perfect way or decision to fix this problem, I am sure there is just something simple which is missing probably in the code but this may do the trick for now. ( I think ).

**Comment by deotern** [comment] 2015-12-04 18:21
That is helpful to me :D Thanks for the info, I have been looking into these for a day, and still no progress.. So, u're meaning /kill is working, right? Hmm, at least i can confirm now bug isnt at Respawn Packet, i think there must be something related to chunk loading etc.. 

Anyway, thanks, i will try to fix this :D

**Comment by ZombiePower** [comment] 2015-12-05 00:42
hm...

**Comment by MCPEPIG** [comment] 2015-12-05 03:57
I think I figured it out.

**Comment by MCPEPIG** [comment] 2015-12-05 04:06
/kill uses the kill function and the kill function sends a RespawnPacket to the target, but attack() or setHealth() doesn't. We could fix it by adding something that will send a player the RespawnPacket if the amount given for setHealth() is 0 and for attack() we could check if the player is alive after the damage.

**Comment by MCPEPIG** [comment] 2015-12-05 04:20
Can u check if the fix works?

**Comment by Naniiii** [comment] 2015-12-05 07:22
Exactly, Pig. Some functions related to attacking do not send the respawning packet. I knew something was fishy when I saw that /kill command is working fine. I think your pull request fixes the issue.

**Comment by Naniiii** [comment] 2015-12-05 08:09
If this bug is completely fixed then you guys can release a new version. Because the respawn bug is critical for some pvp servers so new version is needed.

**Comment by deotern** [comment] 2015-12-05 08:16
We havent test it, so we cant release it yet... Anyway, i wil test it later :)

**Comment by ZombiePower** [comment] 2015-12-05 08:29
You just changed the spacing xD

**Comment by keithkfng** [comment] 2015-12-05 08:29
Not "you', @MCPEPIG lol

**Comment by Naniiii** [comment] 2015-12-05 08:30
Okay guys. I will test it rn.

**Comment by Naniiii** [comment] 2015-12-05 08:37
![img_20151205_103742](https://cloud.githubusercontent.com/assets/16087591/11606924/3cebcd28-9b3c-11e5-8729-467b65e93989.JPG)

**Comment by Naniiii** [comment] 2015-12-05 08:38
Works in pvp battles. Imma test itit with hunger now

**Comment by Naniiii** [comment] 2015-12-05 08:48
WORKS WITH HUNGER TOO
![img_20151205_105016](https://cloud.githubusercontent.com/assets/16087591/11606972/b38d8646-9b3d-11e5-899f-40cb3e5daf74.JPG)

![img_20151205_105025](https://cloud.githubusercontent.com/assets/16087591/11606973/bb446cc4-9b3d-11e5-8071-1b62a0d969c4.JPG)

**Comment by keithkfng** [comment] 2015-12-05 09:05
Then finished & fixed.

**Comment by ZombiePower** [comment] 2015-12-06 03:13
that is not ImagicalMine... Read the top, "alpha build 5"

**Comment by MCPEPIG** [comment] 2015-12-06 03:15
It means he's or she is using 0.13 beta 5...

**Comment by ZombiePower** [comment] 2015-12-06 03:15
isn't that the official build?

**Comment by MCPEPIG** [comment] 2015-12-06 03:16
Yeah....

**Comment by ZombiePower** [comment] 2015-12-06 03:18
so, why did he report it here? xd

**Comment by MCPEPIG** [comment] 2015-12-06 03:20
Cause it's a bug in ImagicalMine/PocketMine and he or she is on a ImagicalMine server using 0.13 Alpha Build 5 which is an official build. Do you even understand anything?

**Comment by ZombiePower** [comment] 2015-12-06 03:24
... I meant if he was using the "official" build (not this one), then he should have reported it to the official Pocketmine team... You said before, that the issue was fixed in ImagicalMine... Think before you write

**Comment by MCPEPIG** [comment] 2015-12-06 03:25
He was using ImagicalMine. Read and think before you do anything.

**Comment by MCPEPIG** [comment] 2015-12-06 03:25
and I said official MCPE build. Read.

**Comment by ZombiePower** [comment] 2015-12-06 03:26
omfg...that what I said^

**Comment by ZombiePower** [comment] 2015-12-06 03:26
nvm.. the issue is fixed by you anyways :P

**Comment by Naniiii** [comment] 2015-12-06 11:12
NO. REOPEN THIS

**Comment by Naniiii** [comment] 2015-12-06 11:12
The bug still exists. Still happens when you slay someone.

**Comment by MCPEPIG** [comment] 2015-12-06 18:40
... Same when you fall to your death

**Comment by keithkfng** [comment] 2015-12-06 20:11
@Naniiii Seriously... Why don't you fix it then? We're not working 24/7. Don't speak to us like that.

**Comment by ZombiePower** [comment] 2015-12-07 00:38
@keithfkng he didn't say anything rude xD

**Comment by keithkfng** [comment] 2015-12-07 04:47
@ZombiePower NO. REOPEN THIS.

**Comment by ZombiePower** [comment] 2015-12-07 05:08
The bug still persists... I would actually thank him for notifying us about the bug.

**Comment by XiangZhao969** [comment] 2015-12-07 09:26
Or the easier way to temporary fix this, use the InstantRespawn plugin - but just a temporary fix :)

**Comment by thebigsmileXD** [comment] 2015-12-07 09:51
xD Thanks  @XiangZhao969
Yea.. you could use it, but thats a plugin, and like always, plugins are buggy.

**Comment by Naniiii** [comment] 2015-12-07 16:08
Hehe lol. I think I figured it out. If you take higher damage than your current helth, you will glitch.

Example : My opponent has 0.5 heart(1 health). I kill him with my hands. Buttons show up

Example : My opponent has 1 heart(2 health). I kill him with my diamond sword. Buttons dont show up

When the damager's final damage is higher than your current health, no respawn buttons will show uup

**Comment by thebigsmileXD** [comment] 2015-12-07 16:11
We.. Already know that.. -.-

**Comment by Naniiii** [comment] 2015-12-07 16:12
So it is not a IM bug?

**Closed** 2015-12-07 16:21 UTC

**Comment by thebigsmileXD** [comment] 2015-12-07 16:29
Haven't said that. Its a PM bug, but the IM-Team might fix it ;)
