### ISSUE TITLE
Minor bugs in inventory in the creative mode.

### ISSUE THREAD

**Issue by Rodrigo294X** [ImagicalCorp/ImagicalMine#116] opened 2015-11-25 00:23 UTC
Raw and cooked fish are duplicated. Heads have skeleton head texture. 2 empty slots. And there is no item that was added in 0.13.0
![screenshot_2015-11-24-22-03-09_1](https://cloud.githubusercontent.com/assets/13842405/11384758/cf945e42-92f9-11e5-90bf-b3056879daf4.jpg)
![screenshot_2015-11-24-22-05-26_1](https://cloud.githubusercontent.com/assets/13842405/11384761/dc99a0fc-92f9-11e5-922c-286ed2e5cdec.jpg)
![screenshot_2015-11-24-22-11-28_1](https://cloud.githubusercontent.com/assets/13842405/11384763/e411579e-92f9-11e5-9d62-c70109049620.jpg)

**Comment by keithkfng** [comment] 2015-11-25 00:23
Lel

**Comment by legoboy0215** [comment] 2015-11-25 01:15
Add it yourself @keithkfng XD I just fixed the bugs.

**Comment by mwvent** [comment] 2015-11-25 02:44
There is nothing wrong outside of Item.php that I can find

There have been quite a few commits made adding items but neglecting to add them to the xTab( functions so that explains the missing ones.

Raw fish and other duplicates is a bit more mysterious - as far as I can see the server is sending each meta value variation of the raw fish but the client is seeing them all as item 0 (so no clownfish, puffer etc..) - yet it works for other items like wool. Does anybody remember if this used to work in 0.12?

**Comment by legoboy0215** [comment] 2015-11-25 05:41
Meta?

**Comment by ZombiePower** [comment] 2015-11-25 05:49
I will have a now at it now

**Comment by thebigsmileXD** [comment] 2015-11-25 06:08
Dont ask dumb questions. http://igtfy.com?minecraft+meta

**Comment by legoboy0215** [comment] 2015-11-25 07:44
What? I meant I was guessing the problem.

**Comment by keithkfng** [comment] 2015-11-25 08:10
Lel

**Comment by SavionLegendZzz** [comment] 2015-11-25 08:12
quick question is invs fixed and c mode(i have fixed c mode skins and invs like 3 days ago but i cant fix chest xD)?

**Comment by keithkfng** [comment] 2015-11-25 08:21
Chests, skins AND inventory bugs have already been fixed by the team.

**Comment by SavionLegendZzz** [comment] 2015-11-25 08:23
Awesome has a phar been made(think you guy should spread the word more :D)

**Comment by keithkfng** [comment] 2015-11-25 08:28
Yes, in the releases folder, or in the releases section of the repo.

**Comment by keithkfng** [comment] 2015-11-25 08:29
@SavionLegendZzz help spread the word - https://mobile.twitter.com/ImagicalCorp/status/669432253253091328

**Comment by ZombiePower** [comment] 2015-11-25 09:21
I beleive the problem itself should be found in Item.php or Inventory.php. unfortunately, I don't have time to help you guys, any more... :( 

This may be one of my last messages on GitHub and Pocketmine, before I stop playing MCPE. 

Hope you guys understand.

**Comment by legoboy0215** [comment] 2015-11-25 11:36
...

**Comment by keithkfng** [comment] 2015-11-25 11:39
So... Who's fixing duplicates?

**Comment by mwvent** [comment] 2015-11-25 14:33
I've submitted a PR for the missing items. The duplicates might need looking at on a protocol level to see why the client is ignoring the meta/damage value. I am happy to do a packet capture but I still haven't learnt to interpret them myself.

**Comment by ZombiePower** [comment] 2015-11-26 06:30
$this->isCreative()){ //Creative mode match 
1916 					$item = $packet->item; 
1917 					$slot = Item::getCreativeItemIndex($item); 
1918 				}else{ 
1919 					$item = $this->inventory->getItem($packet->slot); 
1920 					$slot = $packet->slot; 
1921 				} 
1922  
1923 				if($packet->slot === -1){ //Air 
1924 					if($this->isCreative()){ 
1925 						$found = false; 
1926 						for($i = 0; $i < $this->inventory->getHotbarSize(); ++$i){ 
1927 							if($this->inventory->getHotbarSlotIndex($i) === -1){ 
1928 								$this->inventory->setHeldItemIndex($i); 
1929 								$found = true; 
1930 								break; 
1931 							} 
1932 						} 
1933  
1934 						if(!$found){ //couldn't find a empty slot (error) 
1935 							$this->inventory->sendContents($this); 
1936 							break; 
1937 						} 
1938 					}else{ 
1939 						if($packet->selectedSlot >= 0 and $packet->selectedSlot < 9){ 
1940 							$this->inventory->setHeldItemIndex($packet->selectedSlot); 
1941 							$this->inventory->setHeldItemSlot($packet->slot); 
1942 						}else{ 
1943 							$this->inventory->sendContents($this); 
1944 							break; 
1945 						} 
1946 					} 
1947 				}elseif($item === null or $slot === -1 or !$item->deepEquals($packet->item)){ // packet error or not implemented 
1948 					$this->inventory->sendContents($this); 
1949 					break; 
1950 				}elseif($this->isCreative()){ 
1951 					$this->inventory->setHeldItemIndex($packet->selectedSlot); 
1952 					$this->inventory->setItem($packet->selectedSlot, $item); 
1953 					$this->inventory->setHeldItemSlot($packet->selectedSlot); 
1954 				}else{ 
1955 					if($packet->selectedSlot >= 0 and $packet->selectedSlot < 9){ 
1956 						$this->inventory->setHeldItemIndex($packet->selectedSlot); 
1957 						$this->inventory->setHeldItemSlot($slot); 
1958 					}else{ 
1959 						$this->inventory->sendContents($this); 
1960 						break; 
1961 					} 
1962 				} 
1963  
1964 				$this->inventory->sendHeldItem($this->hasSpawned); 
1965  
1966 				$this->setDataFlag(self::DATA_FLAGS, self::DATA_FLAG_ACTION, false); 
1967 				break; 
1968 			case ProtocolInfo::USE_ITEM_PACKET: 
1969 				if($this->spawned === false or $this->dead === true or $this->blocked){ 
1970 					break; 
1971 				} 
1972  
1973 				$blockVector = new Vector3($packet->x, $packet->y, $packet->z); 
1974  
1975 				$this->craftingType = 0; 
1976  
1977 				if($packet->face >= 0 and $packet->face <= 5){ //Use Block, place 
1978  
1979 					$this->setDataFlag(self::DATA_FLAGS, self::DATA_FLAG_ACTION, false); 
1980  
1981 					if($blockVector->distance($this) > 10 or ($this->isCreative() and $this->isAdventure())){ 
1982  
1983 					}elseif($this->isCreative()){ 
1984 						$item = $this->inventory->getItemInHand(); 
1985 						if($this->level->useItemOn($blockVector, $item, $packet->face, $packet->fx, $packet->fy, $packet->fz, $this) === true){ 
1986 							break; 
1987 						} 
1988 					}elseif(!$this->inventory->getItemInHand()->deepEquals($packet->item)){ 
1989 						$this->inventory->sendHeldItem($this); 
1990 					}else{ 
1991 						$item = $this->inventory->getItemInHand(); 
1992 						$oldItem = clone $item; 
1993 						//TODO: Implement adventure mode checks 
1994 						if($this->level->useItemOn($blockVector, $item, $packet->face, $packet->fx, $packet->fy, $packet->fz, $this)){ 
1995 							if(!$item->deepEquals($oldItem) or $item->getCount() !== $oldItem->getCount()){ 
1996 								$this->inventory->setItemInHand($item, $this); 
1997 								$this->inventory->sendHeldItem($this->hasSpawned); 
1998 							} 
1999 							break; 
2000 						}

**Comment by ZombiePower** [comment] 2015-11-26 06:31
I believe the problem is there^

**Comment by ZombiePower** [comment] 2015-11-26 06:32
as, it isn't allowing items to be saved and get changed by -1 (AIR)

**Comment by thebigsmileXD** [comment] 2015-11-26 06:57
Just clarifying: the "9" is there because its how many slots maximum exist

**Comment by ZombiePower** [comment] 2015-11-26 07:14
yes, I know that

**Comment by thebigsmileXD** [comment] 2015-11-26 08:22
And air has the id 0

**Comment by keithkfng** [comment] 2015-11-26 08:24
I think he knows that...

**Comment by thebigsmileXD** [comment] 2015-11-26 08:32
> as, it isn't allowing items to be saved and get changed by -1 (AIR)

**Comment by keithkfng** [comment] 2015-11-26 08:57
Wow, he doesn't? XD

**Comment by ZombiePower** [comment] 2015-11-26 09:20
I never looked at that before :0 well, still looking for the error throughout the API. Just a quick question. In the official 0.12 #48 build, what was the inventory glitch? ( I heard it was a major bug xD) I will look at that, as it may assist me finding the right spot.

**Comment by keithkfng** [comment] 2015-11-26 09:26
I don't actually know, I never used that bleeding build. In fact, I never use bleeding builds now. I use these builds XD

**Comment by thebigsmileXD** [comment] 2015-11-26 09:56
@keithkfng yeaa.. I also always used stable builds, except when i do pull requests on the 0.11

**Comment by DRedDogPE** [comment] 2015-11-26 16:15
![Blocks](http://i.imgur.com/zqaBT71.png)![Decoration](http://i.imgur.com/4nGmXbl.png)![Tools](http://i.imgur.com/EIq5SnV.png)![Seeds](http://i.imgur.com/8pNrnw7.png)

**Comment by DRedDogPE** [comment] 2015-11-26 16:16
Wait i just noticed ![StoneCutter](http://i.imgur.com/aCKl0TW.png)

**Comment by MCPEPIG** [comment] 2015-11-26 19:07
The stonecutter is kept in creative mode as a decoration block.

**Comment by EnderKenji** [comment] 2015-11-29 18:11
Can Fishing rod be fix?

**Comment by legoboy0215** [comment] 2015-12-04 06:26
What?

**Comment by thebigsmileXD** [comment] 2015-12-04 09:03
@DRedDogPE That is on what build? The screenshots i mean, because i had that bug again in the latest one.

**Comment by MCPEPIG** [comment] 2015-12-05 03:45
I think it's from singleplayer

**Comment by matcracker** [comment] 2015-12-24 22:28
More things are fixed, check in the list of bugs

**Closed by matcracker** 2015-12-24 22:28 UTC
Labels: Bug, Duplicated, Enhancement, Help Needed, In Progress
