### ISSUE TITLE
Spawn Protection does not work

### ISSUE THREAD

**Issue by robske110** [ImagicalCorp/ImagicalMine#292] opened 2015-12-14 19:27 UTC
It did work in Build #323, then i upgraded to the jenkins build and noticed that spawn protection does not work anymore (players can break and place blocks)

**Comment by Driesboy** [comment] 2015-12-15 05:38
Work for me

**Comment by Driesboy** [comment] 2015-12-15 05:39
I work withworldprotect

**Comment by robske110** [comment] 2015-12-15 06:25
I don't even have ANY plugin on my test server but since i started to use the jenkins build everyone can break blocks in the spawn area

**Comment by thebigsmileXD** [comment] 2015-12-15 06:31
Confirmed issue. But! I think its because @aodzip added redstone on off switch to the server.properties. After deleting the config and reconfiguring it should work

**Comment by robske110** [comment] 2015-12-15 12:41
Ok, wil try that

**Comment by robske110** [comment] 2015-12-15 14:07
Still not working!
### Please fix!

**Comment by MCPEPIG** [comment] 2015-12-16 00:08
@thebigsmileXD Stop blaming everything on others.

**Comment by MCPEPIG** [comment] 2015-12-16 01:44
What build are you using now?

**Comment by deotern** [comment] 2015-12-16 09:31
Please note, u MUST have at least an OP on your servee to enable spawn protection... Otherwise, spawn protection will be disabled.. =_= Are u sure there's at least one op on your server?

**Comment by robske110** [comment] 2015-12-16 12:45
Build 50, still there

**Comment by robske110** [comment] 2015-12-16 12:57
Oh, i will check if there is an op on my server...

**Comment by robske110** [comment] 2015-12-16 19:14
Was that op issue
So guys, remember to always have an op on your server :(

**Comment by Driesboy** [comment] 2015-12-17 17:24
No-OP players can break blocks on spawn

**Comment by robske110** [comment] 2015-12-17 19:27
Do you have one op on your server

**Comment by Driesboy** [comment] 2015-12-18 07:24
yes

**Comment by robske110** [comment] 2015-12-18 12:29
Need more info here...
For me it works, but is realy slow (takes 10Sek to replace the blocks, that were broken)

**Comment by Driesboy** [comment] 2015-12-18 14:07
no-OP can break blocks on protect places

**Comment by thebigsmileXD** [comment] 2015-12-18 14:42
Source code or phar? Can you track the load on the server when someone breaks a Block? 100% load?

**Comment by astersx** [comment] 2015-12-21 00:51
There is a hack wich allow to break protection on spawn,  there was many on my server and economyLand fixed this!!!!!  Note: I tested with no-op player and cant break,  but some can!!!

**Comment by Driesboy** [comment] 2015-12-21 19:16
Fix it

**Comment by smyb** [comment] 2015-12-24 00:25
@astersx  :open_mouth:

**Comment by PocketKiller** [comment] 2015-12-31 13:38
Is this fixed?

**Comment by thebigsmileXD** [comment] 2015-12-31 14:02
In my latest test yes

**Comment by Driesboy** [comment] 2015-12-31 14:03
yes

**Comment by Driesboy** [comment] 2015-12-31 14:03
close it work

**Closed** 2015-12-31 14:11 UTC
Labels: Bug, Critical
