### ISSUE TITLE
0.13.1 update - "Invalid or corrupt skin" bug upon join

### ISSUE THREAD

**Issue by Godsoft029** [ImagicalCorp/ImagicalMine#299] opened 2015-12-16 09:27 UTC
I tried to join with my custom skin and with Alex but it dont work

**Comment by keithkfng** [comment] 2015-12-16 09:28
I was about to submit this issue! Thanks.

**Comment by Godsoft029** [comment] 2015-12-16 09:28
How..... So fast???

**Comment by keithkfng** [comment] 2015-12-16 09:30
Hahaha, I saw it in the forums.

**Comment by Jelly9912** [comment] 2015-12-16 09:30
Godsoft029, what is your MCPE version? If you're joining on 0.13.0 with latest build of imagicalmine you will get this message "invalid skin"

**Comment by Godsoft029** [comment] 2015-12-16 09:31
I just updated to 0.13.1 and tried to join a leet server - dont work

**Comment by keithkfng** [comment] 2015-12-16 09:32
No, it doesn't work. We will try fix this issue ASAP. There have been some bug patches in the change log for the update, so I'd expect something must be changed in the ImagicalMine code.

**Comment by Jelly9912** [comment] 2015-12-16 09:33
Oh ok, good luck 👍

**Comment by Godsoft029** [comment] 2015-12-16 09:36
#300

**Comment by keithkfng** [comment] 2015-12-16 09:38
Nope. Check my comment.

**Comment by Godsoft029** [comment] 2015-12-16 09:43
And theres a translation error in German. It says "Ungültiges Skin" but it must be "Ungültiger Skin"

**Comment by keithkfng** [comment] 2015-12-16 09:44
LOL none of our business. It's just Mojang translating errors XD

**Comment by Godsoft029** [comment] 2015-12-16 09:46
Lol

**Comment by Godsoft029** [comment] 2015-12-16 09:48
Lifeboat has the same problem ^^ You can join but when the generating screen dismisses, Minecraft crashes - Sorry for my bad english

**Comment by keithkfng** [comment] 2015-12-16 09:48
LOL they're using Steadfast, that's third-party...

**Comment by Godsoft029** [comment] 2015-12-16 09:51
I think they develop their own software? I just searched the Internet and found that on github: "A modification of Pocketmine 1.3 to support the MCPE 0.9 protocol. Extra features for production systems." Lol 0.9 Protocol

**Comment by thebigsmileXD** [comment] 2015-12-16 10:05
Lol

**Comment by keithkfng** [comment] 2015-12-16 10:08
LOL we should all stop "lolling" and do some work XD

**Comment by keithkfng** [comment] 2015-12-16 10:15
A hacky fix has been done on temp-skin-fix. But it's temporary, and we should look for a long-term solution. Thanks @Godsoft029 for the fix.

**Comment by Driesboy** [comment] 2015-12-16 10:30
please fix !!!!!!

**Comment by keithkfng** [comment] 2015-12-16 10:30
DO YOU READ? We already have.

Download skin fix - http://jenkins.imagicalcorp.ml:8080/job/ImagicalMine-SkinFix/1/

**Comment by Driesboy** [comment] 2015-12-16 10:36
thx man sorry

**Comment by Godsoft029** [comment] 2015-12-16 10:48
Fully working for me

**Comment by Driesboy** [comment] 2015-12-16 10:50
work for me

**Comment by Godsoft029** [comment] 2015-12-16 11:03
Experimental but it works

**Comment by Driesboy** [comment] 2015-12-16 11:34
mc crasht

**Comment by SalmonGER** [comment] 2015-12-16 11:40
Works on Windows 10 Edition and Android. But a girl told me that her mc crashs when she joins, and she uses  iOS. (Sry for my bad english :( )

**Comment by Driesboy** [comment] 2015-12-16 11:40
i have the same problem

**Comment by SalmonGER** [comment] 2015-12-16 11:45
@Driesboy so u use iOS?

**Comment by Driesboy** [comment] 2015-12-16 11:45
yes

**Comment by Driesboy** [comment] 2015-12-16 11:47
only when i use a custom skin

**Comment by Driesboy** [comment] 2015-12-16 12:02
the format from skins changed ?

**Comment by TylerAndrew** [comment] 2015-12-16 12:04
the bug is gone !!

**Comment by SalmonGER** [comment] 2015-12-16 12:06
Im using patch 3 from godsoft. Is it fixed in this version?

**Comment by Driesboy** [comment] 2015-12-16 12:08
#Godsoft029 thx to fix

**Comment by thebigsmileXD** [comment] 2015-12-16 13:09
On iOS it still crashes

**Comment by Sunriser21** [comment] 2015-12-16 14:48
The new Bleeding version fixed the skin bug. Maybe you can find the solution there... :-)

**Comment by thebigsmileXD** [comment] 2015-12-16 15:01
We should just copy the original Player.php.. That would also fix some other problems caused by MCPEPig

**Comment by aodzip** [comment] 2015-12-16 15:02
do these things carefully ， MCPEPig work on player xp

**Comment by xHFx** [comment] 2015-12-16 15:20
Crashes upon playerJoin

**Comment by thebigsmileXD** [comment] 2015-12-16 15:45
Thats the problem xD, PlayHarder actually works better

**Comment by xHFx** [comment] 2015-12-16 15:46
How long before we get a fix?

**Comment by thebigsmileXD** [comment] 2015-12-16 15:49
Let us do. Do not produce too much pressure on the team

**Comment by xHFx** [comment] 2015-12-16 15:56
Just my server and alot of other servers are waiting for this update so players with ios can join. We auto update to 13.1 and we cant join our servers <3 -DR Team

http://dr-pvp.us
http://mcpe-market.com

**Comment by Driesboy** [comment] 2015-12-16 16:22
https://github.com/PocketMine/PocketMine-MP/commit/90c3e66e6b87ad8763669850d70c108f364dcaa2
tip !!!!

**Comment by thebigsmileXD** [comment] 2015-12-16 16:42
Just saying, noone auto-updates :p

**Comment by kam187** [comment] 2015-12-16 17:01
Fixed.

**Comment by Driesboy** [comment] 2015-12-16 17:05
i test in 1 min

**Comment by Driesboy** [comment] 2015-12-16 17:08
work :+1:

**Comment by kam187** [comment] 2015-12-16 17:08
:)

**Comment by Driesboy** [comment] 2015-12-16 17:09
thx driesboy to send a tip

**Comment by Godsoft029** [comment] 2015-12-16 17:12
Yup 👍

**Comment by Godsoft029** [comment] 2015-12-16 17:14
Can someone delete the branch temp skin fix?

**Comment by Driesboy** [comment] 2015-12-16 17:21
work on small servers
dont work on big servers

**Comment by Driesboy** [comment] 2015-12-16 17:23
reopen its not full fixed

**Comment by kam187** [comment] 2015-12-16 17:25
What happens on big servers?  It must be something to do with the player list packet i guess.

**Comment by Driesboy** [comment] 2015-12-16 17:29
i have a mini server with the same plugins 
i have a big server with the same plugins
big crasht 
mini not

**Comment by Godsoft029** [comment] 2015-12-16 17:31
Where is the difference? How many Players are on the bigger server?

**Comment by kam187** [comment] 2015-12-16 17:36
Hmm not sure but i think maybe, possibly, perhaps some more info might help!  Like a crash log :p

**Comment by Driesboy** [comment] 2015-12-16 17:38
public function spawnTo(Player $player){

**Comment by kam187** [comment] 2015-12-16 17:40
Send the full crash from the console. I don't have time to be trawling around files working out what you can already tell me with 2 more lines of a log :P

**Comment by thebigsmileXD** [comment] 2015-12-16 17:41
And where is the crash dump

**Comment by Driesboy** [comment] 2015-12-16 17:47
read!!!!!
i have a mini server with the same plugins (1 my mcpe)
i have a big server with the same plugins (10-> 10 sec after restart)
mcpe on big crasht
mini not

**Comment by Driesboy** [comment] 2015-12-16 17:47
MCPE CRASHT

**Comment by kam187** [comment] 2015-12-16 17:51
:(
Why can't you paste the crash from the console?  You are shouting for a fix but can't even be bothered to send the information we need.  Seems your time is worth more than mine?

**Comment by Godsoft029** [comment] 2015-12-16 17:58
He 
means that the client crashes

**Comment by kam187** [comment] 2015-12-16 18:08
Ahh that's why he wasn't sending the console message lol.

Try after the last commit

**Comment by thebigsmileXD** [comment] 2015-12-16 18:29
Why should it? That makes the Player visible to everyone.
Else you won't see others

**Comment by thebigsmileXD** [comment] 2015-12-16 18:37
But i can understand that you haven't got that. The english was really bad.
Even google translate does a better job.
Anyways, i got "login timeout" on the latest build (55)

**Comment by Driesboy** [comment] 2015-12-16 18:40
sorry for my english

**Comment by Godsoft029** [comment] 2015-12-16 18:41
^^

**Comment by Driesboy** [comment] 2015-12-16 18:42
build 55 work for iOS

**Comment by thebigsmileXD** [comment] 2015-12-16 18:59
56 is a big bug fixed. Also.. Skins are wther black or your own skin.. Every join it was different

**Comment by Driesboy** [comment] 2015-12-16 19:21
Ok i will test it tomorrow
Op 16-dec.-2015 20:06 schreef "Dan" <notifications@github.com>:

**Comment by xHFx** [comment] 2015-12-16 19:29
Have you fixed the IOS crasning

**Comment by thebigsmileXD** [comment] 2015-12-16 19:52
Yes.

**Comment by xHFx** [comment] 2015-12-16 20:09
link

**Comment by keithkfng** [comment] 2015-12-16 20:13
Check Jenkins yourself. I can't be bothered posting links anymore.

**Comment by robske110** [comment] 2015-12-16 20:18
jenkins.imagicalcorp.ml:8080/job/ImagicalMine/
I can...

**Comment by viki2133** [comment] 2015-12-16 20:46
I am on iOS and still on 0.13.0 and I can't join servers but the message is different. What do I do withe links you provided?

**Comment by keithkfng** [comment] 2015-12-16 20:49
You can't do anything, you need to update. The links are for server software only.

**Comment by viki2133** [comment] 2015-12-16 20:54
Oh. Okay then.

**Comment by viki2133** [comment] 2015-12-16 20:56
Well, I have another problem, when I enter a server it doesn't load he terrain, only the playera and starts lagging a lot.

**Comment by viki2133** [comment] 2015-12-16 21:00
Nevermind, it was a connection problem.

**Comment by xHFx** [comment] 2015-12-16 21:15
did they add transfer packet?

**Comment by thebigsmileXD** [comment] 2015-12-16 21:17
You can still join and work on 0.13.1 with 0.13.0 client.

**Comment by robske110** [comment] 2015-12-16 21:28
Idk if the transfer packet was added again, probaly not

**Comment by xHFx** [comment] 2015-12-16 22:00
Lets check and see ?

**Comment by MCPEPIG** [comment] 2015-12-16 22:40
I tested, it's fixed.

**Closed** 2015-12-16 22:41 UTC
Labels: Bug, Critical, Fixed

**Comment by MCPEPIG** [comment] 2015-12-16 22:43
Just checked, transfer packet still not back :/

**Comment by dterweij** [comment] 2015-12-17 17:35
With release ImagicalMine-IC_1.0dev#73.phar Windows 10 Beta Minecraft still have Skin error.

**Comment by Driesboy** [comment] 2015-12-17 18:32
do you use 0.13.1

**Comment by xHFx** [comment] 2015-12-17 18:42
Can anybody help me with MCPE Transfer for DarkRealms ?

**Comment by RedFiire** [comment] 2015-12-17 19:49
hello I 'm using the 0.13.1 version of minecraft I downloaded the file named ImagicalMine - IC_1.0dev I downloaded to solve, now What do I do with it?

**Comment by robske110** [comment] 2015-12-17 19:59
### @RedFiire Please post Not-Issue-Related stuff here: https://gitter.im/ImagicalCorp/ImagicalMine

You install the latest beta of pocketmine: http://pocketmine.net and then replace the pocketmine-mp.phar with the phar you downlaoded from jenkins and rename it to pocketmine-mp.phar!

**Comment by Atief123** [comment] 2015-12-18 13:19
Can anyone help? I have 2 problems 1) If I play the original minecraft and I touch play it crashes. And I have to use MCPE master. 2) when I wanna use a server I touch the server and it says building terrain then it crashes. HELP

**Comment by matcracker** [comment] 2015-12-18 13:30
1)Use the original MC:PE without laucher's mod.

2)This isn't a forum and it isn't a bug releated to ImagicalMine

**Comment by Atief123** [comment] 2015-12-18 13:44
No it's like this, When I use original MCPE when I touch play it crashes

**Comment by thebigsmileXD** [comment] 2015-12-18 14:50
This is offtoppic. Also this is not the normal minecraft!

**Comment by keithkfng** [comment] 2015-12-18 20:13
@Atief123 https://github.com/ImagicalCorp/ImagicalMine/blob/master/CONTRIBUTING.md
