### ISSUE TITLE
Broken Signature

### ISSUE THREAD

**Issue by PocketKiller** [ImagicalCorp/ImagicalMine#305] opened 2015-12-16 16:57 UTC
Hi,
*sigh* when i start my IM server that i downloaded from Jenkins. i found out that Jenkins doesn't make phar properly with devtools (i checked how jenkins works) or it's my fault?
```

Warning: require_once(phar://C:\Users\USER\Desktop\Taha\FlashCraft PE\lobby 1\PocketMine-MP.phar/src/pocketmine/PocketMine.php): failed to open stream: phar "C:\Users\USER\Desktop\Taha\FlashCraft PE\lobby 1\PocketMine-MP.phar" has a broken signature in C:\Users\USER\Desktop\Taha\FlashCraft PE\lobby 1\PocketMine-MP.phar on line 1

Call Stack:
    0.0025     127744   1. {main}() C:\Users\USER\Desktop\Taha\FlashCraft PE\lobby 1\PocketMine-MP.phar:0


Fatal error: require_once(): Failed opening required 'phar://C:\Users\USER\Desktop\Taha\FlashCraft PE\lobby 1\PocketMine-MP.phar/src/pocketmine/PocketMine.php' (include_path='.;.\ext') in C:\Users\USER\Desktop\Taha\FlashCraft PE\lobby 1\PocketMine-MP.phar on line 1

Call Stack:
    0.0025     127744   1. {main}() C:\Users\USER\Desktop\Taha\FlashCraft PE\lobby 1\PocketMine-MP.phar:0

bin\php\php.exe: Exit 255
```
Thanks

**Comment by robske110** [comment] 2015-12-16 19:17
I got that too! Was running from source though, restarted the server and bam it worked again
Ao try to type stop after that and start it again
#Have you tried to turn it off and on again?

**Comment by PocketKiller** [comment] 2015-12-16 19:18
i did, (not running from source) and using an edited start.cmd

**Comment by robske110** [comment] 2015-12-16 19:52
Just try to make a new clean install with build 50?

**Comment by keithkfng** [comment] 2015-12-16 20:14
That seems to be a problem with you only, because my one is running perfectly.

**Comment by robske110** [comment] 2015-12-16 20:26
I had that one too, but after one server restart it worked again...
So again try to reinstall @PocketKiller !

**Comment by PocketKiller** [comment] 2015-12-16 20:41
i did, reinstalled, redownloaded the phar 13 times.. not working!

**Comment by PocketKiller** [comment] 2015-12-16 20:44
if it's my wifi fault i EXPLODEE

**Comment by matcracker** [comment] 2015-12-16 21:00
Use a correct start.cmd

**Comment by PocketKiller** [comment] 2015-12-16 21:01
i reset it already.

**Comment by thebigsmileXD** [comment] 2015-12-16 21:22
>
Warning: require_once(phar://C:\Users\USER\Desktop\Taha\FlashCraft PE\lobby 1\PocketMine-MP.phar/src/pocketmine/PocketMine.php): failed to open stream: phar "C:\Users\USER\Desktop\Taha\FlashCraft PE\lobby 1\PocketMine-MP.phar" has a broken signature in C:\Users\USER\Desktop\Taha\FlashCraft PE\lobby 1\PocketMine-MP.phar on line 1

Call Stack:
    0.0025     127744   1. {main}() C:\Users\USER\Desktop\Taha\FlashCraft PE\lobby 1\PocketMine-MP.phar:0


Fatal error: require_once(): Failed opening required 'phar://C:\Users\USER\Desktop\Taha\FlashCraft PE\lobby 1\PocketMine-MP.phar/src/pocketmine/PocketMine.php' (include_path='.;.\ext') in C:\Users\USER\Desktop\Taha\FlashCraft PE\lobby 1\PocketMine-MP.phar on line 1

Call Stack:
    0.0025     127744   1. {main}() C:\Users\USER\Desktop\Taha\FlashCraft PE\lobby 1\PocketMine-MP.phar:0

bin\php\php.exe: Exit 255

Just saying, spaces have to ve replaced by "_" or just put the whole path into "'s

**Comment by Mules75** [comment] 2015-12-16 22:30
I seem to have the same problem or not ? ... I'm very new to this ...

This is on MCProHosting server. The latest release from GitHub worked (PocketMine-MP_0.13.0dev#517.phar) ... From Jenkins all have this problem.

16.12 23:12:38 [Multicraft] Not restarting crashed server.
16.12 23:12:38 [Multicraft] Server stopped
16.12 23:12:38 [Multicraft] Looks like a crash, check the server console. Return value: 255
16.12 23:12:38 [Multicraft] Server shut down
16.12 23:12:38 [Server] INFO Fatal error: require_once(): Failed opening required 'phar:///PocketMine-MP_1.6_50-Beta.phar/src/pocketmine/PocketMine.php' (include_path='.:') in /PocketMine-MP_1.6_50-Beta.phar on line 1
16.12 23:12:38 [Server] INFO Warning: require_once(phar:///PocketMine-MP_1.6_50-Beta.phar/src/pocketmine/PocketMine.php): failed to open stream: internal corruption of phar "/PocketMine-MP_1.6_50-Beta.phar" (truncated manifest header) in /PocketMine-MP_1.6_50-Beta.phar on line 1
16.12 23:12:38 [Multicraft] Loaded config for "Other: PocketMine-MP Beta"
16.12 23:12:38 [Multicraft] Starting server!
16.12 23:12:38 [Multicraft] Loading server properties
16.12 23:12:38 [Multicraft] Received start command

Read the CONTRIBUTING.md document, don't know yet where to post this issue, so I posted in wrong place ... sorry for that.

**Comment by thebigsmileXD** [comment] 2015-12-16 23:05
> PocketMine-MP_0.13.0dev#517.phar
> Warning: require_once(phar:///PocketMine-MP_1.6_50-Beta.phar/src/pocketmine/PocketMine.php): failed to open stream: internal corruption of phar "/PocketMine-MP_1.6_50-Beta.phar"

Doesn't that explain everything? Your multicraft settings are Incorrect 

> Am 16.12.2015 um 23:55 schrieb Mules75 <notifications@github.com>:
> 
> PocketMine-MP_0.13.0dev#517.phar

**Comment by Mules75** [comment] 2015-12-16 23:51
Sorry, I am a noob on this ... just trying to find some input to fix this. Don't think I have access to the multicraft settings...

**Comment by Mules75** [comment] 2015-12-17 00:09
Bad or strange incomplete download of the .phar file seems to be the problem...grrr. Fixed now.

**Comment by Mules75** [comment] 2015-12-17 00:10
Thanks for the great work! :-)

**Comment by thebigsmileXD** [comment] 2015-12-17 05:53
Welcome

**Comment by robske110** [comment] 2015-12-17 05:56
Is this "fixed" now?

**Comment by robske110** [comment] 2015-12-17 05:58
And am I allowed to post pull requests or are you still angry with me because that string ""?

**Comment by thebigsmileXD** [comment] 2015-12-17 06:12
If you mess anything up we can revert it.

**Comment by aodzip** [comment] 2015-12-17 06:20
This issue is caused by Network unstable , try to download by a download tools , Jenkins works well .

**Comment by keithkfng** [comment] 2015-12-17 06:28
PLEASE DO NOT GO OFF-TOPIC OR USE THE THE ISSUE TRACKER AS A CHAT. - README.md
DO YOU USERS READ? I'M NOT TALKING ABOUT THE TEAM, I'M TALKING ABOUT THE USERS WHO GO OFF-TOPIC AND POST SEPARATE ISSUES ON COMPLETELY DIFFERENT ISSUES.

**Comment by robske110** [comment] 2015-12-17 06:33
Sorry, but where should i do that on gitter?
Back to the issue:
As I said already: Try to run from source!

**Comment by Taki21** [comment] 2015-12-17 12:28
@thebigsmileXD Spaces won't help... I'm looking closely at "require_once"
Question: @PocketKiller : Did you ever open the Phar File? Its having a signature problem on Line 1:
This is what there is in Line 1:

<?php define("pocketmine\\PATH", "phar://". __FILE__ ."/"); require_once("phar://". __FILE__ ."/src/pocketmine/PocketMine.php");  __HALT_COMPILER(); ?>

Question: Did u reinstall whole server using the pocketmine installer or just phar file? o_0

**Comment by aodzip** [comment] 2015-12-19 06:33
This is just caused by internet connection unstable
close

**Closed by aodzip** 2015-12-19 06:33 UTC

**Comment by robske110** [comment] 2015-12-19 06:40
What that can be caused by everything BUT not a bad internet connection
PocketMine starts up without an internet connnection

**Comment by aodzip** [comment] 2015-12-19 07:02
the phar you download is broken by unstable internet
The Jenkins server is in China
you can search The Great Firewall to know why i say unstable

**Comment by aodzip** [comment] 2015-12-19 07:04
I will make a global CDN to solve this later

**Comment by robske110** [comment] 2015-12-19 07:09
Oh, now i understand i'm in germany..

**Comment by thebigsmileXD** [comment] 2015-12-19 07:36
I am also, but it works for me, so i don't think thats the issue.
