### ISSUE TITLE
Potions, Doors, and Flower Pots glitch 

### ISSUE THREAD

**Issue by NML32** [ImagicalCorp/ImagicalMine#47] opened 2015-11-20 20:35 UTC
Potions do not work(Both splash and normal).
All doors other than oak and iron open when placed and lose the bottom half of themselves.
Flower pots don't like to stay for long.

**Comment by DRedDogPE** [comment] 2015-11-20 20:37
Try my version?

**Comment by NML32** [comment] 2015-11-20 20:38
Do you have a link?

**Comment by DRedDogPE** [comment] 2015-11-20 20:39
https://github.com/EliteCrafterz/PocketMine-MP/

**Comment by DRedDogPE** [comment] 2015-11-20 20:39
A whole lot of stuff has been added to that (MORE THAN THIS)

**Comment by NML32** [comment] 2015-11-20 20:40
Thanks.

**Comment by DRedDogPE** [comment] 2015-11-20 20:41
No Problem

**Comment by keithkfng** [comment] 2015-11-20 21:30
Can you update this repo with the fixes? Thanks.

**Comment by DRedDogPE** [comment] 2015-11-20 23:11
@keithkfng Done!

**Comment by DRedDogPE** [comment] 2015-11-20 23:26
Bug | Fixed? | Extra
------------ | ------------- | ------------ 
Potions | N | Added, just u cant use them yet
Doors | Y | Pretty easy fix actually. 
FlowerPots | **N** | Jesus.... these pots are so damn annoying.
FlowerPots | **N** | Cant put flowers inside them. Sometimes have a breaking bug... 
Skulls | N | Visual glitch, cant place, only shows Skeleton Skulls

**Comment by keithkfng** [comment] 2015-11-24 11:41
Is this fixed @legoboy0215?

**Comment by legoboy0215** [comment] 2015-11-24 11:43
No. This is kinda pointless since those are feature requests :P Anyways, I will reopen it :)

**Comment by keithkfng** [comment] 2015-11-24 11:44
More enhancement yes

**Comment by NML32** [comment] 2015-11-27 18:36
On the latest commit #294 Spruce doors are working the other new doors are still glitched as 1/2 doors

**Comment by thebigsmileXD** [comment] 2015-12-02 09:53
FlowerPot.. fixed? has anyone tried yet?

**Comment by NML32** [comment] 2015-12-03 23:48
Flowerpot still turns in to stairs when placed.

**Comment by thebigsmileXD** [comment] 2015-12-04 06:58
I know

**Comment by NML32** [comment] 2015-12-04 14:09
@thebigsmileXD Lol, ok I was just answering your question.

**Comment by EnderKenji** [comment] 2015-12-10 20:04
Iron door & Trapdoorss not working well
![screenshot_2015-12-11-03-53-00](https://cloud.githubusercontent.com/assets/15629214/11727012/4fe8986e-9fbc-11e5-9a04-1b72562a2443.jpg)

**Comment by thebigsmileXD** [comment] 2015-12-11 07:10
I can confirm.. Someone broke the code, maybe me. I'll change them back to original

**Comment by EnderKenji** [comment] 2015-12-13 11:40
Latest build is the same.

**Comment by thebigsmileXD** [comment] 2015-12-13 13:28
Doors do not glich anymore.

**Comment by EnderKenji** [comment] 2015-12-13 16:07
Are you sure? The door still glitch... only can open door once,, cant close door... and trapdoor rotation is weird ._.

**Comment by FienixEC** [comment] 2015-12-13 16:13
Same problem.

**Comment by thebigsmileXD** [comment] 2015-12-13 16:51
Latest build: no glich



> Am 13.12.2015 um 17:13 schrieb FienixEC <notifications@github.com>:
> 
> Same problem.

**Comment by thebigsmileXD** [comment] 2015-12-13 16:54
Latest build: no glich for me



> Am 13.12.2015 um 17:13 schrieb FienixEC <notifications@github.com>:
> 
> Same problem.

**Comment by aodzip** [comment] 2015-12-13 16:57
Latest code : Dark OakDoor glich
Iron Door cant close when redstone power off.

**Comment by thebigsmileXD** [comment] 2015-12-13 17:28
Redstone closing was taken out because it caused that opening doors by hand closes then instantly.

Dark oak door is like every other door.. It should work.
I guess we need a different activation method.

**Comment by aodzip** [comment] 2015-12-13 17:40
Write close code in onRedstoneUpdate()

**Comment by thebigsmileXD** [comment] 2015-12-13 17:49
Yea, and thats causing the problem

**Comment by aodzip** [comment] 2015-12-13 17:50
Try My latest commit , it works perfectly

**Comment by thebigsmileXD** [comment] 2015-12-13 17:59
I might change the way redstone works. And i'll add delay

**Comment by thebigsmileXD** [comment] 2015-12-22 18:33
Update on this issue: When the upper part of a door is updated, it changes to the bottom part..

**Comment by aodzip** [comment] 2015-12-27 13:28
This can close now . I think

**Comment by BlackShadow1** [comment] 2015-12-27 13:34
Potions doesn't work

**Closed** 2015-12-27 19:56 UTC
Labels: Bug, Enhancement, Help Needed, In Progress

**Comment by Grecia10** [comment] 2016-01-31 22:54
Slash potions are baned ? CRASH my server
