### ISSUE TITLE
Uploading CrashDump错误报告

### ISSUE THREAD

**Issue by ibookcc** [ImagicalCorp/ImagicalMine#220] opened 2015-12-05 12:52 UTC
Uploading CrashDump错误报告
PocketMine-MP Crash Dump Sat Dec 5 13:52:15 CST 2015

Error: Uninitialized string offset: -1
File: /src/pocketmine/level/format/mcregion/Chunk
Line: 121
Type: notice

Code:
[112] 		unset($this->nbt->Data);
[113] 		unset($this->nbt->SkyLight);
[114] 		unset($this->nbt->BlockLight);
[115] 		unset($this->nbt->BiomeColors);
[116] 		unset($this->nbt->HeightMap);
[117] 		unset($this->nbt->Biomes);
[118] 	}
[119] 
[120] 	public function getBlockId($x, $y, $z){
[121] 		return ord($this->blocks{($x << 11) | ($z << 7) | $y});
[122] 	}
[123] 
[124] 	public function setBlockId($x, $y, $z, $id){
[125] 		$this->blocks{($x << 11) | ($z << 7) | $y} = chr($id);
[126] 		$this->hasChanged = true;
[127] 	}
[128] 
[129] 	public function getBlockData($x, $y, $z){
[130] 		$m = ord($this->data{($x << 10) | ($z << 6) | ($y >> 1)});
[131] 		if(($y & 1) === 0){

Backtrace:
#0 /src/pocketmine/level/Level(2668): pocketmine\level\format\mcregion\Chunk->getBlockId(integer 15, integer -1, integer 1)
#1 /src/pocketmine/Player(758): pocketmine\level\Level->getSafeSpawn(pocketmine\Player Player(157))
#2 /src/pocketmine/Player(738): pocketmine\Player->doFirstSpawn(boolean)
#3 /src/pocketmine/Player(1687): pocketmine\Player->sendNextChunk(boolean)
#4 /src/pocketmine/Server(2508): pocketmine\Player->checkNetwork(boolean)
#5 /src/pocketmine/Server(2227): pocketmine\Server->tick(boolean)
#6 /src/pocketmine/Server(2105): pocketmine\Server->tickProcessor(boolean)
#7 /src/pocketmine/Server(1706): pocketmine\Server->start(boolean)
#8 /src/pocketmine/PocketMine(464): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/ZF/PocketMine-MP.phar/, string /home/ZF/, string /home/ZF/plugins/)
#9 (1): require_once(string phar:///home/ZF/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 1.6dev #0 [Protocol 38; API 1.13.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux iZ28qyqou4iZ 3.10.0-123.9.3.el7.x86_64 #1 SMP Thu Nov 6 15:06:03 UTC 2014 x86_64
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:
SWorld 1.1.0 by 18WYJ2 & boybook for API(s) 1.0.0
MoreItem 1.2.5 by toybaby for API(s) 1.13.0
Broadcaster 1.13 by EvolSoft for API(s) 1.8.0
Marry 1.2.3 by  for API(s) 1.0.0
DisableFlow 1.0.0 by MUedsa for API(s) 1.8.0
QituShop 1.5.0 by qitu for API(s) 1.0.0
Mobs 1.3 by SavionLegendZzz for API(s) 1.7.0
entPvpc 2.3.3 by cpera for API(s) 1.8.0
PNoCheat 1.2.4 by PeratX for API(s) 1.12.0
Color_chat 1.2.1 by homenear for API(s) 1.12.0
Protection 1.8.0 by zzx for API(s) 1.9.0
WorldProtect 2.0.2 by aliuly for API(s) 1.10.0
FightTheBoss 1.0.1 by Smile for API(s) 1.12.0
EconomyAPI 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
SmartSign_by腐竹CrainL 1.0.0 by CrainL for API(s) 1.0.0
BloodFX 1.0.0 by hoyinm14mc & CyberCube-HK Team for API(s) 1.12.0
FactionsPro 1.4.1 by Tethered_, HostingItAll.com for API(s) 1.12.0
FResidence 1.0.6 by FENGberd for API(s) 1.0.0
MineMOTD 1 by MagicDroidX for API(s) 1.12.0
AshMan 1.0.1 by FENGberd,Alcatraz_Du for API(s) 1.0.0
JoinAndQuit 1.0.1 by guestc for API(s) 1.12.0
PocketGuard 2.1 by MinecrafterJPN for API(s) 1.6.0
MagicTelePortal 1.3.2 didou汉化 by aliuly for API(s) 1.10.0
KBook 1.0.1 by Kevin for API(s) 1.12.0
BSHealth 1.1.0 by bing_shen for API(s) 1.12.0
NanoVip 1.0.0 by FENGberd&Anapopo for API(s) 1.0.0
BanItemAdd 1.2.1 by zzx for API(s) 1.9.0
essentialsTP 1.0.9 by  for API(s) 1.0.0
GParticle 1.6.0 by Einreiz for API(s) 1.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtO4ly20aWv9JFu2akKYIieErMyFWKbCVOZJsJ5fVsBlOqJtAgEQFoGN2QRGX97/ve68ZFSTbt
aLe2aicV20Af7z67wT86OkpEZ+aORkeDo9F0OO52Yq70qzyXeWf2R0dvMpjupFJHvuh0O4lQiq9w
6H0apZGOeBzdiYApnUfpiskwVELPmOPC2rCI47MoxsXZmuezg4ODtUzEwW9nB3PpXwn9JkqF82be
w9kDlfsHGQ0nMHwQi2sRH4QyT7g+SPxcrCKZHpyui/QK1mcI3oD+io2wKYYlwO7A7XZ0zoGl2T87
z/rsYSDn+PfeYDI53J+xetbzaNrzDBLPK7F4HqFxXqyE/j6G9a+DvSjVYiVy5o67rHx23PrZ3Qeq
nrn3KJjHfCPyven4EdxEG2Fa8FAsMn6T7jWXmf3MgnHH031CNHgU0XAbkZlwXgTyLMqVNiiWUsaC
pwRr+Bgsd3I4fQSYEmnwVtxqElQL2ugetIXIrwHaYNx/jDR/Lfyrt0LfyLwNbPwosMFgmzQz47wA
C28DmTwKxO2PPwNknksf3ETmLWjTx6C50/7kEWhK81y3oBzel3nlSnujyegRQJeXvkzBRwtft6zk
VCYZ19EyFqfg9upc8gCMRi5/F77utiAVOoqV573hUXouV6vGKuv6O7h4tbZadH8ki4tVlKoD4vaI
7bnAUS4+FlEuLmXqi73d0T0qKAwg+51/fep2xJPEuT8ViIAKw3NnFvJYiW7Hl4FAmlx3AGA97eki
BWx7z/U6Us6LdKmdFy+55vvfARzXHT66aHG1OY9Wa20Xjh5dSMGquXT8+NIIBH4qY5kru3by6Nof
BYJ8wzO7cvp5qCXAQ1r2iZ6P4BkfBn0azIplHPksLFJfgzRZI9A+v+2y5xv4c7f/B+1wLbZc6CJP
mcyDEuUSt6g/YAv7+9+Z6+6z/2J7z+/wZYrPzzefDCmDQU3KYFiSMnqQFPUQKfAnCiw9pUx3J4Id
M3+d7yEIQ86kDWLN1emapyuwy2MGzi3MqmmD6MOS6KPPyg/N6Z4Eh/0SXQLwG/ILYHVFeL9B+MQ8
b9iLF5DYrBCHpSKicA/n/gJT7Pj4mPUBzad/5+F/5+F/5+H/13m421mJVOQ8xqQHYlLgwhAy3N4k
ENeAfllEcdCZ9SFR5lJLX8LC4WG3w7OIlrnDXh+WrSINr/0d/4MNOb+KoyXu6U0JQpFybIY651Fa
3LLot8Hhx81HWYyi39iw5/Z7fQeyQO+oN+yJeNq7PZxcTkYMYsbizZxdrAv2Vl6zCUSYWX8y6w/Z
+4tTNui7I2ZWAgJsXGadcW/SG8DbHfggvA7gtW8mL6Uq0cMAvcT0UhUJCmW0+CBzlMgfHUuwHei2
pOcSVF7oNeRqjK/u4Yf//GkA8XcpN2DLVyh5kiFM9YA7fBcpByME2JhOup1AZEAk7oY5JUP9sjmQ
cKxaLHYw8pKKGMwXxufvFhcf3v16/hKGbsRSRRpoTaEpBG7eyFy81iJpMFENtdkY9MZtNjRQz5eb
FvVkAk3ybSm1E/0lYuNVu9H/fQ5rfOiURd5goTm6pYxhm4lX1zJeAD0tLg6/XQcNzNtsLC5Ofr14
P28y0VlrnSlw25ubm54AUhBsT1+hnb3heb5pqoXet3XSZueJDIlQIfkG4w5qeBkpRHMWy5sGyc3R
NuH9bZ94814Eij+VFhqIjRYomn+BFVKG1YXPNWhw0/NTVMUvkS4Wa5k1WKuG2nyNt/n6COueyr9L
nJ7XwL6Tjy9Vy7+XaovsLadY8GuYOYd6LA1+u7tr0T/9dvpN5PS8V6mO9OYNT6Gxy3djQaR6fp35
DS7KkSYj4A7brPgZJLSnMivAmQFOz7uK4ng3wudv5elacN2gvBra9uVRm/Q5UK7/0Q6vg28n3mL9
muBK7eWlv26R3xjcZsBtM4ClSCp4/mQs1KixUmuQsYsioGQR1Gw1VVEPtnk53Pbju7vbFhtH385F
jRQK9yYBO3BBmd1uavDRGm57RJ9KnAYnPI6KeCtr/4mgZMB53g2SkBkSdsh8lp8zPJi4WIvvpWqG
qNbwdubYsrJFgsc+T2ViTcyet0XHDgp6BX2FTDYn89cNdhqD28rZ8nmZiiX8uZcxulUdiX5W/uvS
v0P7PrTvI/s+gvdvlIIlw/OEoRxogbDd5GIHUSwSaNYW0Sq9XG684tAd971iysOj0xx7pmbV/PmF
X6gc7KqnqqGBDGgCE54GX1WGxlIGZ/9olqB25AvUr+UmShN3lPjQD5xuliI/LZbC+fFndiF48mRm
XaPxvCVSFt56Xk3iDhyecQpTCqJM01Ebo21OR9t+eiH0WuQiuOyyH6XS0LO+1idx3PPl07HZIAec
17zsrsSzX4WKApH6oslhPbitykmbwbNXb38A/QVPZYo15q+xROzn37y7eNks+MqhBgNuu/rmq8h/
mcsoeLp6o8QKxNf4v5gQTtQaCsMG8XbgC0mglH33JIbSPed3ly+frOw+O8XTpp36OcvETzJKT9Lg
lyJqJunm6BfYWRVCaf/JVHHxbu55bfS7VEx0PvRDwfPmEUdztMEFJKO2RYHO/ZyH0EX9NH/b4mTy
52yqhgrlU4uYLzZ32GmvIr0ulhh1DtrQDhrADkwDDk5xIWIxl7k2h2JVK96e2WqmegMWRIEsvGLi
j468Yjx0J/8rNViis68JFT9/j4dPNVvm/Qum+bO4BvhPZZmE8qsS7eJHwWO9bmbacugLx25LSDmX
ai2ejvoKIuTSmogduHjLU/kfUfM8oRz5QrlQxrm/nKQ8k5l8qhhn0XteTccuyuApntedBM0A0Rj8
Qn/4hD2VRQp6MA87niooBS19xGN1MW8eLTSHtxVy9D9x4NbECEV3G/8OjPwwhwo68uNm4VKPtVmY
bNvUqyjNRXT3VKZU4d3drfFUnedANkTiEjpd1PSgocwEgBN4BP9sXr2xU5mG0Yrhlb+Xe+mzBdfs
pfDZmLnD2didjafs+7cXeOw/xvlE6uDYK/p9Po2Z+Xf0MhL2kcvQPoVKcPuY4z5DhpNBnD92j9zh
AAdv1kC6E0dKH8swxBGeprKAQs3JzEUc99eRuBYJqFEdQ5+PkPC60Mmqfv/YnRBh/NZuUseDfp+A
xbG8ccIYe88SgdnN0ygBq2hBTOSyHFiBBBMZiGMCE8ocCKrGLKA1ZDdf5tV7dp3Z3UEUhpFfxHpz
7BI0ugvSMneU0Fiuq2McputWB23s+M6vB5QQQWMeP+M4Pjs/ucAhY0XOx0LkG4vMDuXQUpaU4HMv
40rdyDw4/hv9B8IotHQUvxZ2I97PVFdYvU0So10wNDTmk0kUQDPeqKNlMJABa12EgaUw6OeVYCVT
jOeCQWfCoN9V8AB25KM6NVsKFqV+XAQigAd2zyIR1kImsDNEANswFQ9Fl0lsehSCZMtc8Cu2kUVu
YbEoZKCbKIwIA6glB9uARA6A34qbCtxBIEIOilHsRqZ/1YxnmeA5Q9EkwKwPBrMB8hl+FGD4voGc
xIpslfMAAPS8FC3ZAJt5KXt2sc4FWLDAQ24W83RV8JVg+L0LicxaPXYfLJY+fnJDQsWtp3jFbLho
bwQCyhpLpL2b6CrKRBDxnsxXB/h2cA4OcynDy9eLd5eT4ZEzuMR9IMYK0Ix5HcInvA7i+rCmnpFp
yfCenAGj9n4UNJXzVMVcg+homgRqNjNgAXgjrQZQrviCraGfj0nPCQA2rlFjpUsqGFfrQgcSncp8
dYT0QBE37QdQxA24C39PJofwdxAO4G93OvSKo7EIDLUn6LcMwwLdx5prQnYdcfYLWj4sIQ9w7EyN
9tliDRs5GrCSQKXFbrTILSRWKLBPiMBgI8T1yfw1rIQoHqAI6wkHBLGUqsHWs1fkbSUgEAXDEMDA
lMFakNjlhlkbg+XWN6vZGX3SQvqIQAEyBWvjQcByoYxRIpl4zw/kcFXkFPYYmOJSoEBAGeJjwWNU
0yq6hrXXPC4E27MYIUbvA3CDDkKCwGDrgJbxUn0Gs4j5bZEs8Yo9ZCdqk/oXXF0x/MgBfKuH8+8V
SARNt+QRV61zCWEZTAVWqy6jE0pmwxpYcxekkIDUFKZGkgpkJRxLihScCpcQ7AWZEvADfpfLWwjB
WoAIgB3ygrQiDYVqyHkdovPiEnTSLov0X0FyOqddgcAUQNa5tZftAQegZzZAiRAPjuVyRpDQkTGe
5xty4x9iuQTBYiZmZhjML4k0hqtErPhyo4EgtjCk9Am5uRkzQQB4uomIMBI2w7xj4JTyVySXMAJr
gQgGoT0lUCGEjxKjUT8wU5DRriTwIdEZUWaAZ0VEOkTYjPU9iiIUsDVEIR78Hycfq5rPEI/59E8R
r7TMCL8NYRU9Fppi4FKYFiHMWGoQ5xZJc5FHktIUOqJCbPQtUEla5Wwu4IE4E6CB0QoHnEEYN6Pw
LqHyTME9QWgYGR6TqZElVEIxRX50dLPMo0SMMMD1ajc2IQQxvMP4gZmPlvfuL0aebeEJ8suEjwlS
kUyQViNgs7diAMQoMlWzOexbPtX+gwRZroeG6xXPl6B8x5dxbKozdK8HpUq2hKTYPczuAcdNeFpQ
Km5SAWVKAYaw3y0DwpYlWFMwQTUMy8CQ1CbWY+9MEqQ3MIe1LOKgIiSC8HGTspp0NFqWEeWg1lG/
b3hkz87IDe4FRrIVs7tiKsxlUsZX3GvnnWZIaugUmLCq2zaFB+ynsQ+LXx8/fFNG3udk8hgNaRAp
w94BuWGmSO6Sb+ZQmCizyMHCAGucGhaCKtVsvQTqdkPnS2m2basPMwBWUGZbE4LBYpc9Ac+UhRwf
OgRhuLa2UCLCiTp1fxaWl6bmU7+qpgPbiE0eXHINPQjWIRzLX4UfWDIbk8gDTcVqZ00oWooqI1Kw
edYMXuUMen6+0Qi7yxy3Yc2Y+Qito0tSwADHExNW6kxLHQKmucAEO6tBsxcGLU099iN0QCDfYyiS
wXJP5++7sBcoWEIAuokCvTYxmxy8Au8Q+Bkb27KgLhgUCaaxtMdOAnCoNY/DA6j+TQ0TCDA0iwhQ
GgOUadMjq9zcgFUXSa9u0fmwBuJx1zg24v0QpVBaAldgNoJMGxP9+3k6L8uEupbHCgg33UCg97CQ
TzPHvlI9Zq0DejaxLFYzW3G8YPgZrbZpBUtKmi7LSUVxbC3KMtOzmpgxt64RFTtQmusC7OVg5RvJ
4l2Yqq2u7Pda7YQo60dmvgE2jRQttcaF3JK6fRChJvuyWxyzZcaqz4YNP3TmgNSCwYGJUkziLfgQ
OLFR0w30IEt9nxpyUVLcs7fvLl7NGAVd+N8voOdKoeciQFGSxVS9EnkWc0VeVU6ftJTl05ffJa9k
Q5SRgBK0GY12M+jbDIKRzCQmNCLsbXHcZiNrQe3hMoSZOniBzooMLrkSDWR7LrjJA1i6bAAT7kMT
Qvu9fXJZJZpUkDVcIGRst+zZBBMQlww+zPxGk9Tb1k0vhgFqgbBywmDA4xu+UQa2hdOw3Vb4JjM6
SWSRNuO/svVaSQSSj9CwXYDQjI8gmMe38hxGA0O7gdFOOpQXHthMxpUK01ouhQG2FCGGITp1wXCF
WqiAmrOYRtyjqLfg15BxsbIrf7biy2xjzwtsIqqqGYoSIX05WIZEG8LCIqZlUoGhOuifkW/yCDVf
OTbpYBYAthTU7xJ7IOMZiidoKQnFScwuFfelRxtNoDRLTbzht4xvSyUzn3GLoDaGliJGuPNXHkSF
auyyOuCWNnJQs9PaHK438qITL6fIArDDRnvsx4IbHHTmtk133dCVpPfu025D3w2PqDmHRrwQVrl2
P7k8jTsKVDVjh98ELZNZEVto9hmT0hZgLyV/dEB4SLQ513PIiIDxEZZsoO4UbaEadW1owMMwkBfV
daVC8YKyyGbsyBR7xhopcJgaw8ICKFPcZREiUEyTwAgiqgZpjCfLCMzeLLHncKY3n5lAhKcIOVdr
ZkZNdrU2YmzXFvGN8xXY5OChTxXraKTKJa3RbJ1FaSjr3WuJyiecvcYZINRARGAq002CJT45iAIB
q4pS7FnsNKuniWL8DQ3jqxWkHnsqUJ23YH2IP4q5eoQdQxDCUw8RhBIzxkxKvrcdzMJMz4wO8tSx
qbkShBmVWS2aZ6d4kkjnWiKWGSarLrwDD3hup8s6DMqSEOpkAeKG9JRiljeTNrcWqCJwygYYZi8J
GjVEAfWm0ibDlSHPwkMtmekSQ02jkQt+RvuAVOII8o3RzKtbjgnXvGDBAvAtEbOSGpoCi8c2ecb+
iY8OZJku9c3/QogmEJZ1SPMUlpgo+wXTtJVn2tSNPXSoS80tpTFFJQOynUAlEQGhNsc3SCesRAA9
MTwFR/+lUFhjmzE8Cp8Nvpt2x0e3bnd4O+wOvnO/CyAVm9C1p3MBLxBmjg/7bAU2rszbaLxPh97i
VosUBUKfyZ1CJmr8gAGNqPEKGWFVfXmf+bjUvqiPcaTF0PzUwjG/6rgzv70wX5UtfShs1vUvIHkM
3sPzesD8PrN8K/K4egmjmD7CB9CuuXsNdVbNrpL6eQ0ebG7TYNHvqnU9mCzNAW+1GIrCTaZrDjRH
goIGu4v5OWHF58yHYq7euwGG6bcd9omN8ULbRc6Zg5dDg/64P4TH56/RMYfToeDjIBiPh4fTiTvq
T/hhfzDgo+UhH05HI/dwCQ21YM8B03yNYqk+sMykim5rodtm3S5wkdFfRRiXH6B2CN+hGIc+h1J1
BGj74XTqTw8PJ+MxoB4eDYZi2F8eTY+CgPCpdSJrESpyLNXmNDLCh8VaXokUkk1ejXwQ/ApighEU
/ZJjw+nyBC/KccEdXkeb+3D8JnEhi9wX9DFExElBAAf2ffr039Cuw9Y=
===END CRASH DUMP===

**Comment by aodzip** [comment] 2015-12-05 17:44
This issue is provide by a Chinese , allow me use Chinese to reply him.
=========================================================
就以国产插件的质量来看，插件里充满了过时的调用与函数声明，极易崩服，我觉得你在汇报错误之前还是去掉所有的插件看看还会不会出现类似的错误比较好。
不然的话，这种汇报是没有意义的
=========================================================
English Version:
you use many "Chinese Version" Plugin , these plugin is more unstable and use many deprecated call . use these plugin will make your server crash easily.
If you want to provide your crash log . I think you should remove all of these plugins , or the crash report is useless.

**Comment by XiangZhao969** [comment] 2015-12-06 04:51
Actually, it isn't. The error caused by some "buggy" coordinate that effected by your old or error map using some world editor and tool that made your map changed inside. Check if you had used that

**Comment by aodzip** [comment] 2015-12-06 05:58
他使用了过时的SWorld和世界保护类插件,以及一些其他的对entity和block有影响的插件，无法判断到底是地图被修改过造成的还是这些插件鬼畜造成的。

He use some outdated plugin like"sworld" , "WorldProtect"  and some plugins affect entity and block . In this situation we can't know this crash is cause by plugin or the core src.

Close this issue.

**Closed** 2015-12-06 06:45 UTC

**Comment by ibookcc** [comment] 2015-12-07 23:08
Thank for your answer.But,Can you tell me some of the English website or forum for the exchange of plug-ins
