### ISSUE TITLE
ArrayOutOfBoundsException

### ISSUE THREAD

**Issue by GAalexandres** [ImagicalCorp/ImagicalMine#290] opened 2015-12-14 07:52 UTC
If a player leave the server when he is on the bedrock level (Y=0) and then he rejoin the server, the server crash with this message: [NOTICE]: ArrayOutOfBoundsException: "Undefined offset: -1" (E_NOTICE) in "/src/pocketmine/level/format/generic/BaseChunk" at line 102. I have to delete the .dat file of the player on the folder "players" to temporary fix this problem, but he lose his inventory.

Here it is the crash dump:

PocketMine-MP Crash Dump Mon Dec 14 07:46:07 GMT 2015

Error: Undefined offset: -1
File: /src/pocketmine/level/format/generic/BaseChunk
Line: 102
Type: notice

Code:
[93] 			return $this->sections[$y >> 4]->setBlock($x, $y & 0x0f, $z, $blockId & 0xff, $meta & 0x0f);
[94] 		}catch(ChunkException $e){
[95] 			$level = $this->getProvider();
[96] 			$this->setInternalSection($Y = $y >> 4, $level::createChunkSection($Y));
[97] 			return $this->sections[$y >> 4]->setBlock($x, $y & 0x0f, $z, $blockId & 0xff, $meta & 0x0f);
[98] 		}
[99] 	}
[100] 
[101] 	public function getBlockId($x, $y, $z){
[102] 		return $this->sections[$y >> 4]->getBlockId($x, $y & 0x0f, $z);
[103] 	}
[104] 
[105] 	public function setBlockId($x, $y, $z, $id){
[106] 		try{
[107] 			$this->sections[$y >> 4]->setBlockId($x, $y & 0x0f, $z, $id);
[108] 			$this->hasChanged = true;
[109] 		}catch(ChunkException $e){
[110] 			$level = $this->getProvider();
[111] 			$this->setInternalSection($Y = $y >> 4, $level::createChunkSection($Y));
[112] 			$this->setBlockId($x, $y, $z, $id);

Backtrace:
#0 /src/pocketmine/level/Level(2668): pocketmine\level\format\generic\BaseChunk->getBlockId(integer 8, integer -1, integer 12)
#1 /src/pocketmine/Player(742): pocketmine\level\Level->getSafeSpawn(pocketmine\Player Player(2))
#2 /src/pocketmine/Player(722): pocketmine\Player->doFirstSpawn(boolean)
#3 /src/pocketmine/Player(1563): pocketmine\Player->sendNextChunk(boolean)
#4 /src/pocketmine/Server(2504): pocketmine\Player->checkNetwork(boolean)
#5 /src/pocketmine/Server(2223): pocketmine\Server->tick(boolean)
#6 /src/pocketmine/Server(2101): pocketmine\Server->tickProcessor(boolean)
#7 /src/pocketmine/Server(1702): pocketmine\Server->start(boolean)
#8 /src/pocketmine/PocketMine(464): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar://D:\Users\Alessandro\Desktop\pocketmine\PocketMine-MP.phar/, string D:\Users\Alessandro\Desktop\pocketmine\, string D:\Users\Alessandro\Desktop\pocketmine\plugins\)
#9 (1): require_once(string phar://D:/Users/Alessandro/Desktop/pocketmine/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

**Comment by thebigsmileXD** [comment] 2015-12-14 07:57
THANKS! Finally we found the reason. I'll fix later

**Comment by GAalexandres** [comment] 2015-12-14 08:03
No problem, Thank you!

**Comment by thebigsmileXD** [comment] 2015-12-14 08:04
Noo, thank you ;)

**Comment by astersx** [comment] 2015-12-14 10:46
Omg if u fix it i will use only and only your server :3,  and how to turn off redstone?

**Comment by thebigsmileXD** [comment] 2015-12-14 12:08
There is no Redstone toggle. We are working on that

**Comment by aodzip** [comment] 2015-12-14 12:52
There is
In server.properties
2015年12月14日 下午8:08，"Dan" <notifications@github.com>写道：

**Comment by thebigsmileXD** [comment] 2015-12-14 13:24
Yea, just saw it 1 hour ago.

**Comment by PocketKiller** [comment] 2015-12-14 16:03
@thebigsmileXD What's the problem with that undefined offset?

**Comment by robske110** [comment] 2015-12-17 06:23
Is this fixed now?

**Comment by robske110** [comment] 2015-12-17 19:30
### I can confirm that it only appears when a player is on 0:
2015-12-17 [19:18:32] [INFO]: borim117[/217.83.82.187:19132] logged in with entity id 810 at (world, 127.3, 0.95, 128.5088)
2015-12-17 [19:18:35] [NOTICE]: StringOutOfBoundsException: "Uninitialized string offset: -1" (E_NOTICE) in "/src/pocketmine/level/format/mcregion/Chunk" at line 126
2015-12-17 [19:18:35] [EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
#### Note the login with coordinate 0

**Comment by robske110** [comment] 2015-12-17 19:34
public function getBlockId($x, $y, $z){
		return ord($this->blocks{($x << 11) | ($z << 7) | $y});
	}
I am saerching for the call of this function, because that does pass that -1, am I right?

**Comment by astersx** [comment] 2015-12-17 19:48
@aodzip Please tell me what i need write in server config to turn off redstone?

And please fix uninitialized offstring -1 error :D

**Comment by robske110** [comment] 2015-12-17 19:57
@astersx Please post Not-Issue-Related stuff here: https://gitter.im/ImagicalCorp/ImagicalMine

just write redstone-calculation=off

**Comment by thebigsmileXD** [comment] 2015-12-17 20:38
It should be x y z not x z y..
That might cause the error

@aodzip we must change the redsrone config to pocketmine.yml!

**Comment by GAalexandres** [comment] 2015-12-17 21:42
The players keep crashing my server, so I've temporary fixed with this:

	public function getBlockId($x, $y, $z){
		if($y = 0){
			$y = 1;
		}
		return $this->sections[$y >> 4]->getBlockId($x, $y & 0x0f, $z);
	}

Let me know if you find a solution, thanks.

**Comment by astersx** [comment] 2015-12-18 06:44
@GAalexandres  It work? I really need  offstring -1 error to be fixed,  becouse im forced to use Always Spawn :(,  if i dont use it server crash :(

**Comment by GAalexandres** [comment] 2015-12-18 11:14
Yeah, u have to set the y = 1 if it is = 0 before the return, but Idk if is
recommended to do this, but anyway it works

**Comment by robske110** [comment] 2015-12-18 12:33
#### To the team members:
THIS IS AN CRITICAL BUG, WE NOW KNOW WHERE IT DOES COME FROM!
But does anyone know why "-1" on 0?

**Comment by astersx** [comment] 2015-12-18 13:55
@GAalexandres  I can do that but pocketmine plugin dont support the phar app i use . I will never use devtools,  never.

**Comment by astersx** [comment] 2015-12-18 13:59
Hi,  it should  be if y <= 0  , becouse sometimes crash even if is -1 -2.....

**Comment by robske110** [comment] 2015-12-18 14:28
Use http://pmt.pocketmine.net

**Comment by astersx** [comment] 2015-12-18 14:41
Failure,  invalid upload.
:(

**Comment by thebigsmileXD** [comment] 2015-12-18 14:43
I think because it should return x y z instead of x z y. Looked at it yesterday. The error is in the Spawn player core in player.php.

**Comment by astersx** [comment] 2015-12-18 14:46
But if i make y = 1,  is no more 0,  so it should spawn player normaly on the bedrock

**Comment by thebigsmileXD** [comment] 2015-12-18 14:55
You don't use DevTools because you do not know how to use it. And you create things without this knowledge?
Its so easy.
Put the folder of your plugin in the plugins folder like you would run it from source folder. Then type
> makeplugin <Plugin name, case sensetive. You can get the name by doing /pl.>

Then everything is done

**Comment by thebigsmileXD** [comment] 2015-12-18 14:56
But most servers don't just have 1 layer of bedrock! Your code would force them to spawn at y=0

**Comment by astersx** [comment] 2015-12-18 15:00
Is better than crashing :),  if not i can make y=2 so it will spawn with 1 block higher :)

**Comment by thebigsmileXD** [comment] 2015-12-18 15:06
For the exact code look at my DynMapPE.

**Comment by thebigsmileXD** [comment] 2015-12-18 15:08
Is it so hard?
y = getHighestBlockAt.

**Comment by astersx** [comment] 2015-12-18 15:09
I understand but.... Im not familiar with mcpe functions,  i only know php

**Comment by astersx** [comment] 2015-12-18 15:10
+players spawn at y=0 becouse they make homes on bedrock in theyr mine so im sure they will have space to spawn

**Comment by astersx** [comment] 2015-12-18 15:16
Hi,  im trying to phar it but devtools just dont work :|,  is on /plugins/devtools/pocket/src   ,  /makeplugin dont work and /makeserver    i dont know from were it takes the resources to make pocketmine plugin

**Comment by Godsoft029** [comment] 2015-12-18 15:18
Just do it in plugin folder /plugin/<Your Plugin>/src

**Comment by astersx** [comment] 2015-12-18 15:19
What? /makeserver  ?

**Comment by astersx** [comment] 2015-12-18 15:21
so were is /plugins i need to add src from pocketmine? and then /makeserver?

**Comment by thebigsmileXD** [comment] 2015-12-18 15:46
WOW! AND YOU WANT TO HOST A SERVER?
Plugins.. REALLY?! You do not see the folder? I give up

**Comment by astersx** [comment] 2015-12-18 15:48
my bad :D,  i didnt mean were is plugins,  i mean really just put it /plugins folder?  And didnt work :|

**Comment by astersx** [comment] 2015-12-18 15:59
And i was asking "So were is /plugins i need to add src file?" I didnt ask "So were is /plugins?"
...........

**Comment by PocketKiller** [comment] 2015-12-18 16:01
stop going off-topic.

**Comment by astersx** [comment] 2015-12-18 16:06
Screw this you know how to abuse ppl,  his stupid post is not delleted only mine,  Screw IM,  fake plugin.

**Comment by astersx** [comment] 2015-12-18 16:07
I didnt post there for u to make fun of me retarded kid

**Comment by PocketKiller** [comment] 2015-12-18 16:08
@astersx i am not making fun of you

**Comment by PocketKiller** [comment] 2015-12-18 16:09
talk in https://gitter.im/ImagicalCorp/ImagicalMine

**Comment by astersx** [comment] 2015-12-18 16:51
Not you  is @thebigsmileXD

**Comment by PocketKiller** [comment] 2015-12-18 16:52
it's me.. i did that

**Comment by astersx** [comment] 2015-12-18 20:10
I did it,  i run pocketmine of source thanks to a tutorial ;)
And thebigsmileXD told me fake info!!

And i will make y=1 if y <= 0....  Hope it will work

______________________________________
 thebigsmileXD commented 5 hours ago
You don't use DevTools because you do not know how to use it. And you create things without this knowledge?
Its so easy.
Put the folder of your plugin in the plugins folder like you would run it from source folder. Then type
 makeplugin <Plugin name, case sensetive. You can get the name by doing /pl.>
Then everything is done

**Comment by keithkfng** [comment] 2015-12-18 20:17
@astersx If you speak to a team member like that again, you will be banned from getting any support. Please review your messages, and edit them to the right context. Please also look at the contributing guidelines before posting - https://github.com/ImagicalCorp/ImagicalMine/blob/master/CONTRIBUTING.md

**Comment by astersx** [comment] 2015-12-18 20:18
I found how to get that error,  boys,  now i have proof that hackers who can break bedrock exist.
They break 1 bedrock and put slab,  then go on slab quitand relogin = server crash!!!!

**Comment by astersx** [comment] 2015-12-18 20:19
Im so sooory :(!!!  I will try to wach out my language :D

**Comment by astersx** [comment] 2015-12-18 20:19
In the first place was imposible to spawn on y = 0

**Comment by astersx** [comment] 2015-12-18 20:22
And need to edit all chunks files,  for 64 bits,  32 bits....  And any code like that need edited

**Comment by astersx** [comment] 2015-12-18 20:29
I fixed it :),  I fixed only mcregion 32 and 62 bits :),  if u need the files i can send to you :)

**Comment by thebigsmileXD** [comment] 2015-12-18 20:46
This Information was totally right, not my fault if you haven't understood it

**Comment by thebigsmileXD** [comment] 2015-12-18 20:48
Just saying.. The error is not in the chunk format, its in the Player.php in the spawn part.. I had no time to fix it yet. Do never ever edit the region files!

**Comment by astersx** [comment] 2015-12-18 21:04
I did it and work ;)

**Comment by robske110** [comment] 2015-12-18 22:15
Then make a pull request please

**Comment by keithkfng** [comment] 2015-12-18 22:56
No, never edit the region files.

**Comment by astersx** [comment] 2015-12-19 00:15
Hi,  it is bad if u add complex code in region files,  but only to set y to 1 if is <1 it does not harm,  i did it and server work sooo well ... no crashes :3  + you need to know what you edit , not like a blind ban, " Hey i saw a code :0,  lets put it in region =)) "

I can remake that crash in any server if i have creative,  i tested code on a test server before using it :)

**Comment by robske110** [comment] 2015-12-19 06:38
Just show us the code ;)

**Comment by GAalexandres** [comment] 2015-12-19 06:52
The code is above, but Idk if it is safe to use, it's just a temporary fix
while the team find a solution

**Closed** 2015-12-24 23:55 UTC
